### PR TITLE
Fix namespace cause of Name Error.

### LINKED ISSUE #33: NameError undefined local variable or method `client' for Glueby::Internal::Wallet::TapyrusCoreWalletAdapter
I run `broadcast` through `Glueby::Internal::Wallet`.
I use wallet adapter is `Glueby::Internal::Wallet::TapyrusCoreWalletAdapter`.

using commit: `03baa9bf87980e90e9048cfa5d6babe1aa7b3c18`

expect:
can broadcast and return txid.

actual:
```
NameError (undefined local variable or method `client' for #<Glueby::Internal::Wallet::TapyrusCoreWalletAdapter:0x00007fd9d19a2830>)
```

I think you mistake namespace of method. it add name `RPC` above `client`.

https://github.com/chaintope/glueby/blob/master/lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb#L110

### PR DESCRIPTION
**Pull request by JunOkumura**
fixed #33.
Please review and merge.

### CODE REVIEW

File: lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb [hunk 1]
```diff
@@ -107,7 +107,7 @@ def sign_tx(wallet_id, tx, prevtxs = [])
         end
 
         def broadcast(wallet_id, tx)
-          client.sendrawtransaction(tx.to_hex)
+          RPC.client.sendrawtransaction(tx.to_hex)
         end
```
Comment (azuchi) [inline lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb:111]: This method doesn't seem to need to take `wallet_id` as an argument. Also, if you are passing a `wallet_id`, it would be correct to say `perform_as (wallet_id) ..` instead of `RPC.client ...`.

@Yamaguchi what do you think?

**Review by azuchi — CHANGES_REQUESTED** [review]

File: lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb (hunk 1 above)
Comment (Yamaguchi) [reply lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb:111]: I prefer to  use `perform_as(wallet_id)` than RPC.client directly.

Comment (azuchi) [reply lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb:111]: @JunOkumura Can you change to use `perform_as(wallet_id)` ?

Comment (JunOkumura) [reply lib/glueby/internal/wallet/tapyrus_core_wallet_adapter.rb:111]: ok. I try it soon.

**Review by azuchi — APPROVED** [review]
